<a href="https://colab.research.google.com/github/uzair011/CN5022-AI/blob/main/Task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <span style="color:red"> Objective: <span>
Understanding the linear regression algorithm by constructing a linear regression model for a dataset. Analyse the results and provide comments and conclusions.

# <span style="color:red"> Instructions: <span>
For this task, we will make use of the salary_data.csv in the dataset folder.

#### **salary_data.csv**

This dataset consists of one feature (independent variable), **YearsExperience** and one label (dependent variable), **Salary**. Depending on the years of working experience, the dataset provides the salary corresponding the experience.

Now, you are required to develop a linear regression model in order to predict the salary of a new employee coming to the company with certain number of year of experience.

Using Jupiter Notebook, open the notebook called **Task2.ipynb**:

### <span style="color:purple"> a) Load the necessary libraries for the task<span>

Notes: In this task, we will make use of the following libraries:
1. numpy
2. pandas
3. matplotlib

In [2]:
# put your code here
%matplotlib inline

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

### <span style="color:purple"> b) Now, we import this salary_data.csv file using the Pandas method, make sure that the dataset is in the same folder as your Task2.ipynb. Read the first 5 rows of the dataset for observation. <span>

**Notes: refer to task one for an example.**

In [5]:
# put your code here
df = pd.read_csv("salary_data.csv") # import/load the data file

print(df.head(5))

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891


### <span style="color:purple"> c) Split the dataset into X, the independent variable and y, the dependent variable / label <span>

Notes: The dataset is loaded in b) as a whole dataset. However, in order for us to develop a linear model, we need to splt the dataset into the independent variable, x and dependent variable y.

Coding guide: In order to do so, we will make use of the Pandas function iloc for selecting, Boolean & Setting. This function have the the following syntax:

### **For example:**

In [18]:
# spliting the dataset into X,  the independent variable and y
# put your code here

# X = df.iloc[:, 0].values # X= independent variable; select the whole column
# y = df.iloc[:, 1].values # y=dependent variable; select the whole column

X = df.iloc[:, :-1].values  # Independent variable(s)
y = df.iloc[:, 1].values   # Dependent variable

print(X)
print(X.shape)
print("\n",y)
print(y.shape)

[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]]
(30, 1)

 [ 39343  46205  37731  43525  39891  56642  60150  54445  64445  57189
  63218  55794  56957  57081  61111  67938  66029  83088  81363  93940
  91738  98273 101302 113812 109431 105582 116969 112635 122391 121872]
(30,)


### <span style="color:purple"> d) Split the X and y into training and test set using method in sklearn package. <span>

In [20]:
help(train_test_split)

Help on function train_test_split in module sklearn.model_selection._split:

train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)
    Split arrays or matrices into random train and test subsets.
    
    Quick utility that wraps input validation,
    ``next(ShuffleSplit().split(X, y))``, and application to input data
    into a single call for splitting (and optionally subsampling) data into a
    one-liner.
    
    Read more in the :ref:`User Guide <cross_validation>`.
    
    Parameters
    ----------
    *arrays : sequence of indexables with same length / shape[0]
        Allowed inputs are lists, numpy arrays, scipy-sparse
        matrices or pandas dataframes.
    
    test_size : float or int, default=None
        If float, should be between 0.0 and 1.0 and represent the proportion
        of the dataset to include in the test split. If int, represents the
        absolute number of test samples. If None, the value is set to

In [21]:
#split X and Y into training and testing set using method
# put your code here

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[ 7.9]
 [ 2.9]
 [ 5.1]
 [ 3.2]
 [ 4.5]
 [ 8.2]
 [ 6.8]
 [ 1.3]
 [10.5]
 [ 3. ]
 [ 2.2]
 [ 5.9]
 [ 6. ]
 [ 3.7]
 [ 3.2]
 [ 9. ]
 [ 2. ]
 [ 1.1]
 [ 7.1]
 [ 4.9]
 [ 4. ]]
[[ 1.5]
 [10.3]
 [ 4.1]
 [ 3.9]
 [ 9.5]
 [ 8.7]
 [ 9.6]
 [ 4. ]
 [ 5.3]]
[101302  56642  66029  64445  61111 113812  91738  46205 121872  60150
  39891  81363  93940  57189  54445 105582  43525  39343  98273  67938
  56957]
[ 37731 122391  57081  63218 116969 109431 112635  55794  83088]


### <span style="color:purple"> e) Generate a linear regression model, called regressor, using the training set <span>
**(Hints: Use the LinearRegression class in the sklearn.linear_model package)**

In [ ]:
# generate linear regression model
# put your code here



### <span style="color:purple">f) Predict the test set results <span>

In [ ]:
# predit test set result
# put your code here


### <span style="color:purple"> g) Visualise the training set results using a scatterplot, using the following code: <span>

In [ ]:
# Visualising the Training set results using scatterplot
# put your code here


### <span style="color:purple"> h) Modify the code above to visualise the test set results using a scatterplot <span>

In [ ]:
# Visualising the Test set results using scatterplot
# put your code here


### <span style="color:purple"> Question 1: From the plots, what is the estimated salary for a new employee with 8 years’ experience? <span>

The estimated salary for a new employee with 8 year's experience is between ___________________

### <span style="color:purple"> Upload the Task2.html file to Moodle via the submission link<span>