<a href="https://colab.research.google.com/github/uzair011/CN5022-AI/blob/main/Week4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <span style="color:red"> Objective: <span>
Understanding the multiple linear regression algorithm by constructing a multiple linear regression model for a dataset. Analyse the results and provide comments and conclusions.

# <span style="color:red"> Instructions: <span>
For this task, we will make use of the 50_startups.csv

#### **50_startups.csv**

This dataset consists of 4 features (independent variable), **R&D spend**, **Administration**, **Marketing Spend** and one label (dependent variable), **Profit**. Depending on features, the dataset provides the corresponding profits

### <span style="color:purple"> a) Load the necessary libraries for the task<span>

Notes: In this task, we will make use of the following libraries:
1. numpy
2. pandas
3. matplotlib

In [ ]:
# import library for the notebook
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
# read in the dataset
dataset =  pd.read_csv('50_startups.csv')
dataset.head() # inspect the dataset

R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

### <span style="color:purple"> c) Split the dataset into X, the independent variable and y, the dependent variable / label <span>

In [ ]:
# spliting the dataset into X,  the independent variable and y
# put your code here

X = dataset.iloc[:, :-1].values # all the row, all the colum except the last column (-1)
y = dataset.iloc[:, -1].values  # the last column

In [ ]:
# display the independent variable
X

array([[165349.2 , 136897.8 , 471784.1 ],
       [162597.7 , 151377.59, 443898.53],
       [153441.51, 101145.55, 407934.54],
       [144372.41, 118671.85, 383199.62],
       [142107.34,  91391.77, 366168.42],
       [131876.9 ,  99814.71, 362861.36],
       [134615.46, 147198.87, 127716.82],
       [130298.13, 145530.06, 323876.68],
       [120542.52, 148718.95, 311613.29],
       [123334.88, 108679.17, 304981.62],
       [101913.08, 110594.11, 229160.95],
       [100671.96,  91790.61, 249744.55],
       [ 93863.75, 127320.38, 249839.44],
       [ 91992.39, 135495.07, 252664.93],
       [119943.24, 156547.42, 256512.92],
       [114523.61, 122616.84, 261776.23],
       [ 78013.11, 121597.55, 264346.06],
       [ 94657.16, 145077.58, 282574.31],
       [ 91749.16, 114175.79, 294919.57],
       [ 86419.7 , 153514.11,      0.  ],
       [ 76253.86, 113867.3 , 298664.47],
       [ 78389.47, 153773.43, 299737.29],
       [ 73994.56, 122782.75, 303319.26],
       [ 67532.53, 105751.03, 3047

In [ ]:
# display the dependent variable
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

### <span style="color:purple"> d) Split the X and y into training and test set using method in sklearn package. <span>

In [ ]:
# split X and Y into training and testing set using method
# put your code here

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)
# test data is 1.3 of the dataset, random_state to fix the process of the implementation to allow similar input splits

### <span style="color:purple"> e) Generate a linear regression model, called regressor, using the training set <span>
**(Hints: Use the LinearRegression class in the sklearn.linear_model package)**

In [ ]:
# generate linear regression model
# put your code here

from sklearn.linear_model import LinearRegression
LR = LinearRegression()
LR.fit(X_train, y_train)

LinearRegression()

### <span style="color:purple">f) Predict the test set results <span>

In [ ]:
# predit test set result
# put your code here

y_pred = LR.predict(X_test)

In [ ]:
X_test

array([[ 66051.52, 182645.56, 118148.2 ],
       [100671.96,  91790.61, 249744.55],
       [101913.08, 110594.11, 229160.95],
       [ 27892.92,  84710.77, 164470.71],
       [153441.51, 101145.55, 407934.54],
       [ 72107.6 , 127864.55, 353183.81],
       [ 20229.59,  65947.93, 185265.1 ],
       [ 61136.38, 152701.92,  88218.23],
       [ 73994.56, 122782.75, 303319.26],
       [142107.34,  91391.77, 366168.42],
       [ 55493.95, 103057.49, 214634.81],
       [ 46014.02,  85047.44, 205517.64],
       [ 75328.87, 144135.98, 134050.07],
       [ 46426.07, 157693.92, 210797.67],
       [ 91749.16, 114175.79, 294919.57],
       [130298.13, 145530.06, 323876.68],
       [119943.24, 156547.42, 256512.92]])

In [ ]:
y_pred

array([106297.59966882, 132926.07997436, 134362.77842228,  71519.46921658,
       180650.71715655, 115248.2571595 ,  64939.68480136,  99726.11825428,
       114940.23331478, 169718.80610512,  96249.07005881,  87336.2065521 ,
       112030.13596157,  91975.69916321, 128433.62518338, 162036.7231283 ,
       152289.76520475])

In [ ]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94,  96778.92,  96479.51,
       105733.54,  96712.8 , 124266.9 , 155752.6 , 132602.65])

### <span style="color:purple">The model performance R^2<span>

In [ ]:
print('Train Score: ', LR.score(X_train, y_train)*100, "%")
print('Test Score: ', LR.score(X_test, y_test)*100, "%")

### <span style="color:purple">The equation of the regression model<span>

In [ ]:
print("The coeficients: ", LR.coef_)

The coeficients:  [0.80219763 0.05708141 0.03071646]


In [ ]:
print("The y-intercept: ", LR.intercept_)

The y-intercept:  39256.467337726426


![image.png](attachment:image.png)

![image.png](attachment:image.png)

Resources from: https://www.javahabit.com/2019/02/10/part-5-ml-mltr-backward-elimination/

### <span style="color:purple">Step 2: Create a MLR model using all the features / independent variables<span>
### <span style="color:purple">Step 3: If p-value > 0.05, then go to step 4<span>

In [ ]:
import statsmodels.api as sm
X_opt = X[:, [0,1,2]]
X_opt = sm.add_constant(X)
X_opt

array([[1.0000000e+00, 1.6534920e+05, 1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 1.6259770e+05, 1.5137759e+05, 4.4389853e+05],
       [1.0000000e+00, 1.5344151e+05, 1.0114555e+05, 4.0793454e+05],
       [1.0000000e+00, 1.4437241e+05, 1.1867185e+05, 3.8319962e+05],
       [1.0000000e+00, 1.4210734e+05, 9.1391770e+04, 3.6616842e+05],
       [1.0000000e+00, 1.3187690e+05, 9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 1.3461546e+05, 1.4719887e+05, 1.2771682e+05],
       [1.0000000e+00, 1.3029813e+05, 1.4553006e+05, 3.2387668e+05],
       [1.0000000e+00, 1.2054252e+05, 1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 1.2333488e+05, 1.0867917e+05, 3.0498162e+05],
       [1.0000000e+00, 1.0191308e+05, 1.1059411e+05, 2.2916095e+05],
       [1.0000000e+00, 1.0067196e+05, 9.1790610e+04, 2.4974455e+05],
       [1.0000000e+00, 9.3863750e+04, 1.2732038e+05, 2.4983944e+05],
       [1.0000000e+00, 9.1992390e+04, 1.3549507e+05, 2.5266493e+05],
       [1.0000000e+00, 1.1994324e+

In [ ]:
MLR_ols = sm.OLS(y, X_opt).fit()
MLR_ols.summary(xname=['constant','R&D spend', 'Administration', 'Marketing Spend'])

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Thu, 22 Feb 2024   Prob (F-statistic):           4.53e-30
Time:                        14:43:10   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
constant         5.012e+04   6572.353      7.626      0.000    3.69e+04    6.34e+04
R&D spend           0.8057      0.045     17.846      0.000       0.715       0.897
Administration     -0.0268      0.051     -0.526      0.602      -0.130       0.076
Marketing Spend     0.0272      0.016      1.655      0.105      -0.006       0.060
==============================================================================
Omnibus:                       14.838   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.442
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.586   Cond. No.                     1.40e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

![image.png](attachment:image.png)
![image.png](attachment:image.png)
![image.png](attachment:image.png)
![image.png](attachment:image.png)

Resources from: https://www.datarobot.com/blog/ordinary-least-squares-in-python/

### <span style="color:purple">Step 4: Remove the variable and rebuild the model<span>

In [ ]:
X_opt=X[:,[0,2]]
X_opt = sm.add_constant(X_opt)
X_opt

array([[1.0000000e+00, 1.6534920e+05, 4.7178410e+05],
       [1.0000000e+00, 1.6259770e+05, 4.4389853e+05],
       [1.0000000e+00, 1.5344151e+05, 4.0793454e+05],
       [1.0000000e+00, 1.4437241e+05, 3.8319962e+05],
       [1.0000000e+00, 1.4210734e+05, 3.6616842e+05],
       [1.0000000e+00, 1.3187690e+05, 3.6286136e+05],
       [1.0000000e+00, 1.3461546e+05, 1.2771682e+05],
       [1.0000000e+00, 1.3029813e+05, 3.2387668e+05],
       [1.0000000e+00, 1.2054252e+05, 3.1161329e+05],
       [1.0000000e+00, 1.2333488e+05, 3.0498162e+05],
       [1.0000000e+00, 1.0191308e+05, 2.2916095e+05],
       [1.0000000e+00, 1.0067196e+05, 2.4974455e+05],
       [1.0000000e+00, 9.3863750e+04, 2.4983944e+05],
       [1.0000000e+00, 9.1992390e+04, 2.5266493e+05],
       [1.0000000e+00, 1.1994324e+05, 2.5651292e+05],
       [1.0000000e+00, 1.1452361e+05, 2.6177623e+05],
       [1.0000000e+00, 7.8013110e+04, 2.6434606e+05],
       [1.0000000e+00, 9.4657160e+04, 2.8257431e+05],
       [1.0000000e+00, 9.174

In [ ]:
MLR_ols = sm.OLS(y, X_opt).fit()
MLR_ols.summary(xname=['constant','R&D spend', 'Marketing Spend'])

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Thu, 22 Feb 2024   Prob (F-statistic):           2.16e-31
Time:                        14:43:10   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
constant         4.698e+04   2689.933     17.464      0.000    4.16e+04    5.24e+04
R&D spend           0.7966      0.041     19.266      0.000       0.713       0.880
Marketing Spend     0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

### <span style="color:purple">Step 3: If p-value > 0.05, remove the variable and rebuild the model </span>

In [ ]:
X_opt=X[:,[0]]
X_opt = sm.add_constant(X_opt)
X_opt

array([[1.0000000e+00, 1.6534920e+05],
       [1.0000000e+00, 1.6259770e+05],
       [1.0000000e+00, 1.5344151e+05],
       [1.0000000e+00, 1.4437241e+05],
       [1.0000000e+00, 1.4210734e+05],
       [1.0000000e+00, 1.3187690e+05],
       [1.0000000e+00, 1.3461546e+05],
       [1.0000000e+00, 1.3029813e+05],
       [1.0000000e+00, 1.2054252e+05],
       [1.0000000e+00, 1.2333488e+05],
       [1.0000000e+00, 1.0191308e+05],
       [1.0000000e+00, 1.0067196e+05],
       [1.0000000e+00, 9.3863750e+04],
       [1.0000000e+00, 9.1992390e+04],
       [1.0000000e+00, 1.1994324e+05],
       [1.0000000e+00, 1.1452361e+05],
       [1.0000000e+00, 7.8013110e+04],
       [1.0000000e+00, 9.4657160e+04],
       [1.0000000e+00, 9.1749160e+04],
       [1.0000000e+00, 8.6419700e+04],
       [1.0000000e+00, 7.6253860e+04],
       [1.0000000e+00, 7.8389470e+04],
       [1.0000000e+00, 7.3994560e+04],
       [1.0000000e+00, 6.7532530e+04],
       [1.0000000e+00, 7.7044010e+04],
       [1.0000000e+00, 6.

In [ ]:
MLR_ols = sm.OLS(y, X_opt).fit()
MLR_ols.summary(xname=['contant','R&D spend'])

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Thu, 22 Feb 2024   Prob (F-statistic):           3.50e-32
Time:                        14:43:10   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
contant     4.903e+04   2537.897     19.320      0.000    4.39e+04    5.41e+04
R&D spend      0.8543      0.029     29.151      0.000       0.795       0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.536
Skew:                          -0.911   Prob(JB):                     9.44e-05
Kurtosis:                       5.361   Cond. No.                     1.65e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# <span style="color:purple">Build the final model</span>

In [ ]:
X_final = X[:,[0,2]]
X_final

array([[165349.2 , 471784.1 ],
       [162597.7 , 443898.53],
       [153441.51, 407934.54],
       [144372.41, 383199.62],
       [142107.34, 366168.42],
       [131876.9 , 362861.36],
       [134615.46, 127716.82],
       [130298.13, 323876.68],
       [120542.52, 311613.29],
       [123334.88, 304981.62],
       [101913.08, 229160.95],
       [100671.96, 249744.55],
       [ 93863.75, 249839.44],
       [ 91992.39, 252664.93],
       [119943.24, 256512.92],
       [114523.61, 261776.23],
       [ 78013.11, 264346.06],
       [ 94657.16, 282574.31],
       [ 91749.16, 294919.57],
       [ 86419.7 ,      0.  ],
       [ 76253.86, 298664.47],
       [ 78389.47, 299737.29],
       [ 73994.56, 303319.26],
       [ 67532.53, 304768.73],
       [ 77044.01, 140574.81],
       [ 64664.71, 137962.62],
       [ 75328.87, 134050.07],
       [ 72107.6 , 353183.81],
       [ 66051.52, 118148.2 ],
       [ 65605.48, 107138.38],
       [ 61994.48,  91131.24],
       [ 61136.38,  88218.23],
       [

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y, test_size = 1/3, random_state = 0)

from sklearn.linear_model import LinearRegression
LR = LinearRegression()
LR.fit(X_train, y_train)

y_pred = LR.predict(X_test)

In [ ]:
print('Train Score: ', LR.score(X_train, y_train)*100, "%")
print('Test Score: ', LR.score(X_test, y_test)*100, "%")
print("The coeficients: ", LR.coef_)
print("The y-intercept: ", LR.intercept_)

Train Score:  95.44855917548342 %
Test Score:  92.8406870739455 %
The coeficients:  [0.81924415 0.02698594]
The y-intercept:  45766.26520877379
